name: partae
channels:
  - default
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3
  - numpy=1 # For Tensorboard https://github.com/tensorflow/tensorboard/issues/6874
  - llvm-openmp<16 # For CPU affinity pytorch issues (https://github.com/pytorch/pytorch/issues/102269)
  - pytorch
  - lightning
  - pytorch-cuda=12.1
  - torchvision
  - transformers
  - opencv
  - matplotlib
  - pip
  - flask
  - prometheus_client
  - imagesize
  - gunicorn
  - jpeg
  - pillow
  - natsort
  - termcolor
  - openpyxl
  - tensorboard
  - tensorboardX
  - pip:
      - torch-tb-profiler
